const {
  withDangerousMod,
  withAppBuildGradle,
  withMainApplication,
  withAndroidManifest,
  AndroidConfig,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Config plugin for the native `GucAuth` Android module (on-device NTLM client
 * that replaced the old Vercel proxy). Because the `android/` folder is a build
 * artifact (git-ignored, regenerated by `expo prebuild`), this plugin recreates
 * everything the module needs on every prebuild:
 *
 *   1. The Kotlin sources (GucAuthModule.kt / GucAuthPackage.kt).
 *   2. The Apache HttpClient dependency in app/build.gradle.
 *   3. Registration of GucAuthPackage in MainApplication.kt.
 *   4. The FileProvider `<provider>` in AndroidManifest.xml.
 *   5. The res/xml/gucauth_file_paths.xml resource.
 *
 * The canonical native sources live in ./gucauth and are the source of truth.
 */

const HTTPCLIENT_DEP = 'cz.msebera.android:httpclient:4.4.1.2';
const TEMPLATE_DIR = path.join(__dirname, 'gucauth');
const FILE_PROVIDER_AUTHORITY = '${applicationId}.gucauth.fileprovider';

function getPackage(config) {
  const pkg = config.android && config.android.package;
  if (!pkg) {
    throw new Error('withGucAuth: expo.android.package must be set in app config.');
  }
  return pkg;
}

// 1. Copy the Kotlin sources + file_paths resource into the generated project.
const withGucAuthNativeFiles = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const pkg = getPackage(cfg);
      const androidRoot = cfg.modRequest.platformProjectRoot; // .../android

      const javaDir = path.join(
        androidRoot,
        'app/src/main/java',
        ...`${pkg}.gucauth`.split('.')
      );
      fs.mkdirSync(javaDir, { recursive: true });

      for (const name of ['GucAuthModule.kt', 'GucAuthPackage.kt']) {
        const template = fs.readFileSync(path.join(TEMPLATE_DIR, name), 'utf8');
        // The templates declare `package com.anonymous.unilink.gucauth`; retarget
        // it to whatever the app's real package is so a package rename still works.
        const contents = template.replace(
          /com\.anonymous\.unilink\.gucauth/g,
          `${pkg}.gucauth`
        );
        fs.writeFileSync(path.join(javaDir, name), contents);
      }

      const xmlDir = path.join(androidRoot, 'app/src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.copyFileSync(
        path.join(TEMPLATE_DIR, 'gucauth_file_paths.xml'),
        path.join(xmlDir, 'gucauth_file_paths.xml')
      );

      return cfg;
    },
  ]);

// 2. Add the Apache HttpClient dependency to app/build.gradle.
const withGucAuthGradle = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes(HTTPCLIENT_DEP)) return cfg;
    cfg.modResults.contents = cfg.modResults.contents.replace(
      /dependencies\s*\{/,
      (match) => `${match}\n    implementation("${HTTPCLIENT_DEP}")`
    );
    return cfg;
  });

// 3. Register GucAuthPackage in MainApplication.kt.
const withGucAuthMainApplication = (config) =>
  withMainApplication(config, (cfg) => {
    const pkg = getPackage(cfg);
    let src = cfg.modResults.contents;

    const importLine = `import ${pkg}.gucauth.GucAuthPackage`;
    if (!src.includes(importLine)) {
      src = src.replace(/(^package .*$)/m, `$1\n\n${importLine}`);
    }

    if (!src.includes('add(GucAuthPackage())')) {
      // Insert right inside the packages.apply { ... } block (robust across the
      // small wording changes Expo makes to the example comment above it).
      src = src.replace(
        /(PackageList\(this\)\.packages\.apply\s*\{)/,
        `$1\n              add(GucAuthPackage())`
      );
    }

    cfg.modResults.contents = src;
    return cfg;
  });

// 4. Add the FileProvider <provider> to AndroidManifest.xml.
const withGucAuthProvider = (config) =>
  withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.provider = app.provider || [];

    const exists = app.provider.some(
      (p) => p.$ && p.$['android:authorities'] === FILE_PROVIDER_AUTHORITY
    );
    if (!exists) {
      app.provider.push({
        $: {
          'android:name': 'androidx.core.content.FileProvider',
          'android:authorities': FILE_PROVIDER_AUTHORITY,
          'android:exported': 'false',
          'android:grantUriPermissions': 'true',
        },
        'meta-data': [
          {
            $: {
              'android:name': 'android.support.FILE_PROVIDER_PATHS',
              'android:resource': '@xml/gucauth_file_paths',
            },
          },
        ],
      });
    }
    return cfg;
  });

module.exports = function withGucAuth(config) {
  config = withGucAuthNativeFiles(config);
  config = withGucAuthGradle(config);
  config = withGucAuthMainApplication(config);
  config = withGucAuthProvider(config);
  return config;
};
